// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjhkESM_skybbEIwnjzNckbM7VOZ0xgVs',
    appId: '1:467320692272:web:cc3410e565948073e517f5',
    messagingSenderId: '467320692272',
    projectId: 'ecommerce-88804',
    authDomain: 'ecommerce-88804.firebaseapp.com',
    storageBucket: 'ecommerce-88804.appspot.com',
    measurementId: 'G-B1ZDYCGF62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBigVmhne2P3_u96mJml7EIG7NxkjnJnpI',
    appId: '1:467320692272:android:5957f9692abe11d3e517f5',
    messagingSenderId: '467320692272',
    projectId: 'ecommerce-88804',
    storageBucket: 'ecommerce-88804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB94Jkuuz6Iqn1u-4q3SEOEB6MvWL1Ct34',
    appId: '1:467320692272:ios:581c27da19c32afbe517f5',
    messagingSenderId: '467320692272',
    projectId: 'ecommerce-88804',
    storageBucket: 'ecommerce-88804.appspot.com',
    iosClientId: '467320692272-atum9f2kishjvbgqlpvtn2joaegnsda4.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB94Jkuuz6Iqn1u-4q3SEOEB6MvWL1Ct34',
    appId: '1:467320692272:ios:581c27da19c32afbe517f5',
    messagingSenderId: '467320692272',
    projectId: 'ecommerce-88804',
    storageBucket: 'ecommerce-88804.appspot.com',
    iosClientId: '467320692272-atum9f2kishjvbgqlpvtn2joaegnsda4.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFirebase',
  );
}
